# Generated by Django 5.2.4 on 2025-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100, null=True)),
                ("apellido", models.CharField(max_length=100, null=True)),
                ("telefono", models.CharField(max_length=20, null=True)),
                ("correo", models.EmailField(max_length=254, null=True)),
                ("fecha_nacimiento", models.DateField(null=True)),
                ("ciudad", models.CharField(max_length=100, null=True)),
                ("programa", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
