# Generated by Django 5.2.4 on 2025-07-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo del Programa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('nivel_formacion', models.CharField(choices=[('AUX', 'Auxiliar'), ('OPE', 'Operario'), ('TEC', 'Tecnico'), ('TGL', 'Tecnologo'), ('ESP', 'Especializacion Tecnologica'), ('COM', 'Complementario')], max_length=3, verbose_name='Nivel de Formacion')),
                ('modalidad', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('MIX', 'Mixta')], default='PRE', max_length=3, verbose_name='Modalidad')),
                ('duracion_meses', models.PositiveIntegerField(verbose_name='Duracion en meses')),
                ('duracion_horas', models.PositiveIntegerField(verbose_name='Duracion en Horas')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Programa')),
                ('competencias', models.TextField(verbose_name='Competencias a Desarrollar')),
                ('perfil_egreso', models.TextField(verbose_name='Pefil de Egreso')),
                ('requisitos', models.TextField(verbose_name='Requisitos de Ingreso')),
                ('centro_formacion', models.CharField(max_length=200, verbose_name='Centro de Formacion')),
                ('regional', models.CharField(max_length=100, verbose_name='Regional')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('SUS', 'Suspendido'), ('CAN', 'Cancelado')], default='ACT', max_length=3, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creacion del Programa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Programa de Formacion',
                'verbose_name_plural': 'Programas de Formacion',
                'ordering': ['nombre'],
            },
        ),
    ]
